version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/app/nginx.conf:/etc/nginx/sites-available/default
      - ./docker/app/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_management_module
      MYSQL_USER: laravel
      MYSQL_PASSWORD: Password1234!
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge